kumuluzee:
  name: lairbnb-reservations
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/ReservationsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/reservations
      username: postgres
      password: postgres
      max-pool-size: 20