kumuluzee:
  name: lairbnb-reservations
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/ReservationsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/reservations
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/ReservationsDS
      etcd-health-check:
        connection-url: http://192.168.99.100:2379/health
      http-health-check:
        - connection-url: http://192.168.99.100:8080/v1/users
        - connection-url: http://192.168.99.100:8081/v1/lairs
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
    - name: reservations-endpoint
      url-pattern: /v1/reservations/*


service-properties:
  service:
    healthy: true
  external-services:
    user-service:
      enabled: true
    lair-service:
      enabled: true